// DOCORE: 음식 키워드 목록을 Supabase 데이터베이스에 다시 질입하는 스크립트

import { config } from 'dotenv';
config({ path: '.env.local' });

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
  throw new Error('Supabase URL or Service Role Key missing. Check your .env.local');
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

const foodList = [
   // ===================== 식사 (meal) 100개 =====================
   { kor_name: '국밥', type: 'meal' },
   { kor_name: '삼겹살', type: 'meal' },
   { kor_name: '돈까스', type: 'meal' },
   { kor_name: '치킨', type: 'meal' },
   { kor_name: '햄버거', type: 'meal' },
   { kor_name: '피자', type: 'meal' },
   { kor_name: '샐러드', type: 'meal' },
   { kor_name: '파스타', type: 'meal' },
   { kor_name: '라멘', type: 'meal' },
   { kor_name: '초밥', type: 'meal' },
   { kor_name: '스테이크', type: 'meal' },
   { kor_name: '쌀국수', type: 'meal' },
   { kor_name: '카레', type: 'meal' },
   { kor_name: '순대국', type: 'meal' },
   { kor_name: '짜장면', type: 'meal' },
   { kor_name: '짬뽕', type: 'meal' },
   { kor_name: '냉면', type: 'meal' },
   { kor_name: '회덮밥', type: 'meal' },
   { kor_name: '오므라이스', type: 'meal' },
   { kor_name: '닭갈비', type: 'meal' },
   { kor_name: '부대찌개', type: 'meal' },
   { kor_name: '감자탕', type: 'meal' },
   { kor_name: '소바', type: 'meal' },
   { kor_name: '찜닭', type: 'meal' },
   { kor_name: '곰탕', type: 'meal' },
   { kor_name: '도삭면', type: 'meal' },
   { kor_name: '마라탕', type: 'meal' },
   { kor_name: '샤브샤브', type: 'meal' },
   { kor_name: '우동', type: 'meal' },
   { kor_name: '김밥', type: 'meal' },
   { kor_name: '로스트치킨', type: 'meal' },
   { kor_name: '삼계탕', type: 'meal' },
   { kor_name: '도시락', type: 'meal' },
   { kor_name: '브런치세트', type: 'meal' },
   { kor_name: '바베큐플래터', type: 'meal' },
   { kor_name: '칼국수', type: 'meal' },
   { kor_name: '잔치국수', type: 'meal' },
   { kor_name: '김치찌개', type: 'meal' },
   { kor_name: '된장찌개', type: 'meal' },
   { kor_name: '비빔밥', type: 'meal' },
   { kor_name: '스파게티', type: 'meal' },
   { kor_name: '양식정식', type: 'meal' },
   { kor_name: '불고기정식', type: 'meal' },
   { kor_name: '스시세트', type: 'meal' },
   { kor_name: '치즈돈까스', type: 'meal' },
   { kor_name: '매운갈비찜', type: 'meal' },
   { kor_name: '사골곰탕', type: 'meal' },
   { kor_name: '연어덮밥', type: 'meal' },
   { kor_name: '참치회덮밥', type: 'meal' },
   { kor_name: '육회비빔밥', type: 'meal' },
   { kor_name: '닭한마리', type: 'meal' },
   { kor_name: '새우튀김덮밥', type: 'meal' },
   { kor_name: '가츠동', type: 'meal' },
   { kor_name: '규동', type: 'meal' },
   { kor_name: '차슈라멘', type: 'meal' },
   { kor_name: '미트볼파스타', type: 'meal' },
   { kor_name: '까르보나라', type: 'meal' },
   { kor_name: '라자냐', type: 'meal' },
   { kor_name: '마르게리타피자', type: 'meal' },
   { kor_name: '고르곤졸라피자', type: 'meal' },
   { kor_name: '봉골레파스타', type: 'meal' },
   { kor_name: '오코노미야끼', type: 'meal' },
   { kor_name: '야키소바', type: 'meal' },
   { kor_name: '불고기덮밥', type: 'meal' },
   { kor_name: '카츠산도', type: 'meal' },
   { kor_name: '타코라이스', type: 'meal' },
   { kor_name: '버터치킨커리', type: 'meal' },
   { kor_name: '치킨마크니', type: 'meal' },
   { kor_name: '탄두리치킨', type: 'meal' },
   { kor_name: '포케볼', type: 'meal' },
   { kor_name: '비프타코', type: 'meal' },
   { kor_name: '치킨타코', type: 'meal' },
   { kor_name: '새우타코', type: 'meal' },
   { kor_name: '베트남쌀국수', type: 'meal' },
   { kor_name: '분짜', type: 'meal' },
   { kor_name: '월남쌈', type: 'meal' },
   { kor_name: '치킨까스', type: 'meal' },
   { kor_name: '스페셜커리', type: 'meal' },
   { kor_name: '훈제연어샐러드', type: 'meal' },
   { kor_name: '멕시칸부리또', type: 'meal' },
   { kor_name: '오리주물럭', type: 'meal' },
   { kor_name: '코다리조림', type: 'meal' },
   { kor_name: '홍합찜', type: 'meal' },
   { kor_name: '양식런치코스', type: 'meal' },
   { kor_name: '일식런치코스', type: 'meal' },
   // 🍩 snack 100개
   { kor_name: '붕어빵', type: 'snack' },
   { kor_name: '호떡', type: 'snack' },
   { kor_name: '과일컵', type: 'snack' },
   { kor_name: '요거트', type: 'snack' },
   { kor_name: '마카롱', type: 'snack' },
   { kor_name: '타코야끼', type: 'snack' },
   { kor_name: '츄러스', type: 'snack' },
   { kor_name: '핫도그', type: 'snack' },
   { kor_name: '도넛', type: 'snack' },
   { kor_name: '샌드위치', type: 'snack' },
   { kor_name: '프레첼', type: 'snack' },
   { kor_name: '초코바나나', type: 'snack' },
   { kor_name: '와플', type: 'snack' },
   { kor_name: '에그타르트', type: 'snack' },
   { kor_name: '쿠키', type: 'snack' },
   { kor_name: '컵케이크', type: 'snack' },
   { kor_name: '크레페', type: 'snack' },
   { kor_name: '스콘', type: 'snack' },
   { kor_name: '브라우니', type: 'snack' },
   { kor_name: '베이글', type: 'snack' },
   { kor_name: '아몬드빼빼로', type: 'snack' },
   { kor_name: '치즈케이크', type: 'snack' },
   { kor_name: '젤라또', type: 'snack' },
   { kor_name: '팥빙수', type: 'snack' },
   { kor_name: '딸기빙수', type: 'snack' },
   { kor_name: '망고빙수', type: 'snack' },
   { kor_name: '수박화채', type: 'snack' },
   { kor_name: '카스테라', type: 'snack' },
   { kor_name: '찹쌀도넛', type: 'snack' },
   { kor_name: '단팥빵', type: 'snack' },
   { kor_name: '치즈스틱', type: 'snack' },
   { kor_name: '감자튀김', type: 'snack' },
   { kor_name: '핫케이크', type: 'snack' },
   { kor_name: '옥수수구이', type: 'snack' },
   { kor_name: '군밤', type: 'snack' },
   { kor_name: '군고구마', type: 'snack' },
   { kor_name: '모닝빵', type: 'snack' },
   { kor_name: '브런치플레이트', type: 'snack' },
   { kor_name: '샐러드', type: 'snack' },
   { kor_name: '아보카도토스트', type: 'snack' },
   { kor_name: '바나나우유', type: 'snack' },
   { kor_name: '초코우유', type: 'snack' },
   { kor_name: '멜론우유', type: 'snack' },
   { kor_name: '치즈볼', type: 'snack' },
   { kor_name: '버터프레첼', type: 'snack' },
   { kor_name: '카라멜팝콘', type: 'snack' },
   { kor_name: '콘샐러드', type: 'snack' },
   { kor_name: '크림치즈베이글', type: 'snack' },
   { kor_name: '피넛버터샌드', type: 'snack' },
   { kor_name: '딸기요거트', type: 'snack' },
   { kor_name: '블루베리요거트', type: 'snack' },
   { kor_name: '피넛쿠키', type: 'snack' },
   { kor_name: '아몬드초코볼', type: 'snack' },
   { kor_name: '초코칩쿠키', type: 'snack' },
   { kor_name: '땅콩크래커', type: 'snack' },
   { kor_name: '오징어땅콩', type: 'snack' },
   { kor_name: '호두과자', type: 'snack' },
   { kor_name: '잉글리시머핀', type: 'snack' },
   { kor_name: '토스트샌드위치', type: 'snack' },
   { kor_name: '피자토스트', type: 'snack' },
   { kor_name: '시리얼볼', type: 'snack' },
   { kor_name: '초콜릿브라우니', type: 'snack' },
   { kor_name: '치즈타르트', type: 'snack' },
   { kor_name: '커스터드푸딩', type: 'snack' },
   { kor_name: '미니도넛', type: 'snack' },
   { kor_name: '에그샐러드샌드위치', type: 'snack' },
   { kor_name: '마요네즈샌드위치', type: 'snack' },
   { kor_name: '햄샌드위치', type: 'snack' },
   { kor_name: '참치샌드위치', type: 'snack' },
   { kor_name: '닭가슴살샐러드', type: 'snack' },
   { kor_name: '닭가슴살랩', type: 'snack' },
   { kor_name: '크로크무슈', type: 'snack' },
   { kor_name: '햄치즈베이글', type: 'snack' },
   { kor_name: '갈릭브레드', type: 'snack' },
   { kor_name: '버터갈릭바게트', type: 'snack' },
   { kor_name: '브라우니바', type: 'snack' },
   { kor_name: '애플파이', type: 'snack' },
   { kor_name: '고구마파이', type: 'snack' },
   { kor_name: '체다치즈스틱', type: 'snack' },
   { kor_name: '고르곤졸라피자', type: 'snack' },
   { kor_name: '고구마피자', type: 'snack' },
   { kor_name: '페퍼로니피자', type: 'snack' },
   { kor_name: '마르게리타피자', type: 'snack' },
   { kor_name: '연어샐러드', type: 'snack' },
   { kor_name: '파인애플샐러드', type: 'snack' },
   { kor_name: '오렌지샐러드', type: 'snack' },
   { kor_name: '그릭요거트', type: 'snack' },
   { kor_name: '치즈플래터', type: 'snack' },
   { kor_name: '하몽플래터', type: 'snack' },
   { kor_name: '과일샐러드볼', type: 'snack' },
   { kor_name: '망고스무디', type: 'snack' },
   { kor_name: '딸기스무디', type: 'snack' },
   { kor_name: '블루베리스무디', type: 'snack' },
   // ===================== 술안주 (alcohol) 100개 =====================
{ kor_name: '곱창구이', type: 'alcohol' },
{ kor_name: '막창구이', type: 'alcohol' },
{ kor_name: '돼지껍데기', type: 'alcohol' },
{ kor_name: '삼겹살', type: 'alcohol' },
{ kor_name: '닭똥집볶음', type: 'alcohol' },
{ kor_name: '닭발', type: 'alcohol' },
{ kor_name: '양꼬치', type: 'alcohol' },
{ kor_name: '오돌뼈', type: 'alcohol' },
{ kor_name: '닭날개구이', type: 'alcohol' },
{ kor_name: '문어숙회', type: 'alcohol' },
{ kor_name: '오징어숙회', type: 'alcohol' },
{ kor_name: '새우구이', type: 'alcohol' },
{ kor_name: '조개구이', type: 'alcohol' },
{ kor_name: '홍합탕', type: 'alcohol' },
{ kor_name: '해물파전', type: 'alcohol' },
{ kor_name: '김치전', type: 'alcohol' },
{ kor_name: '감자전', type: 'alcohol' },
{ kor_name: '굴전', type: 'alcohol' },
{ kor_name: '두부김치', type: 'alcohol' },
{ kor_name: '순대볶음', type: 'alcohol' },
{ kor_name: '골뱅이무침', type: 'alcohol' },
{ kor_name: '치킨', type: 'alcohol' },
{ kor_name: '파닭', type: 'alcohol' },
{ kor_name: '양념치킨', type: 'alcohol' },
{ kor_name: '후라이드치킨', type: 'alcohol' },
{ kor_name: '감바스', type: 'alcohol' },
{ kor_name: '치즈플래터', type: 'alcohol' },
{ kor_name: '하몽', type: 'alcohol' },
{ kor_name: '브루스케타', type: 'alcohol' },
{ kor_name: '프라이드포테이토', type: 'alcohol' },
{ kor_name: '어니언링', type: 'alcohol' },
{ kor_name: '피쉬앤칩스', type: 'alcohol' },
{ kor_name: '크림치즈새우', type: 'alcohol' },
{ kor_name: '로제떡볶이', type: 'alcohol' },
{ kor_name: '마늘빵', type: 'alcohol' },
{ kor_name: '오징어튀김', type: 'alcohol' },
{ kor_name: '새우튀김', type: 'alcohol' },
{ kor_name: '고구마튀김', type: 'alcohol' },
{ kor_name: '김말이튀김', type: 'alcohol' },
{ kor_name: '닭강정', type: 'alcohol' },
{ kor_name: '소시지야채볶음', type: 'alcohol' },
{ kor_name: '오돌뼈볶음', type: 'alcohol' },
{ kor_name: '스팸구이', type: 'alcohol' },
{ kor_name: '참치회', type: 'alcohol' },
{ kor_name: '연어회', type: 'alcohol' },
{ kor_name: '광어회', type: 'alcohol' },
{ kor_name: '우럭회', type: 'alcohol' },
{ kor_name: '멍게', type: 'alcohol' },
{ kor_name: '개불', type: 'alcohol' },
{ kor_name: '해삼', type: 'alcohol' },
{ kor_name: '산낙지', type: 'alcohol' },
{ kor_name: '고등어구이', type: 'alcohol' },
{ kor_name: '꽁치구이', type: 'alcohol' },
{ kor_name: '삼치구이', type: 'alcohol' },
{ kor_name: '장어구이', type: 'alcohol' },
{ kor_name: '버터오징어구이', type: 'alcohol' },
{ kor_name: '닭꼬치', type: 'alcohol' },
{ kor_name: '야끼소바', type: 'alcohol' },
{ kor_name: '스키야키', type: 'alcohol' },
{ kor_name: '곱창전골', type: 'alcohol' },
{ kor_name: '부대찌개', type: 'alcohol' },
{ kor_name: '닭도리탕', type: 'alcohol' },
{ kor_name: '짬뽕탕', type: 'alcohol' },
{ kor_name: '차돌된장찌개', type: 'alcohol' },
{ kor_name: '쭈꾸미볶음', type: 'alcohol' },
{ kor_name: '낙지볶음', type: 'alcohol' },
{ kor_name: '삼겹살김치찜', type: 'alcohol' },
{ kor_name: '꼬막비빔밥', type: 'alcohol' },
{ kor_name: '불곱창', type: 'alcohol' },
{ kor_name: '연어샐러드', type: 'alcohol' },
{ kor_name: '훈제오리', type: 'alcohol' },
{ kor_name: '돼지불백', type: 'alcohol' },
{ kor_name: '양념게장', type: 'alcohol' },
{ kor_name: '간장게장', type: 'alcohol' },
{ kor_name: '명란구이', type: 'alcohol' },
{ kor_name: '명란파스타', type: 'alcohol' },
{ kor_name: '버터구이관자', type: 'alcohol' },
{ kor_name: '치즈감자구이', type: 'alcohol' },
{ kor_name: '떡갈비', type: 'alcohol' },
{ kor_name: '미니버거', type: 'alcohol' },
{ kor_name: '버팔로윙', type: 'alcohol' },
{ kor_name: '나쵸치즈', type: 'alcohol' },
{ kor_name: '피자', type: 'alcohol' },
{ kor_name: '핫윙', type: 'alcohol' },
{ kor_name: '레몬새우', type: 'alcohol' },
{ kor_name: '칠리새우', type: 'alcohol' },
{ kor_name: '크랩케이크', type: 'alcohol' },
{ kor_name: '베이컨말이야채', type: 'alcohol' },
{ kor_name: '카프레제샐러드', type: 'alcohol' },
{ kor_name: '아보카도샐러드', type: 'alcohol' },
{ kor_name: '시저샐러드', type: 'alcohol' },
{ kor_name: '아보카도명란덮밥', type: 'alcohol' },
{ kor_name: '바질토마토샐러드', type: 'alcohol' },
{ kor_name: '감자샐러드', type: 'alcohol' },
{ kor_name: '훈제연어롤', type: 'alcohol' },
{ kor_name: '스모크햄샐러드', type: 'alcohol' },
{ kor_name: '브루스케타샐러드', type: 'alcohol' },
{ kor_name: '토마토바질파스타', type: 'alcohol' },
];

const slugify = (text: string) => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '-').toLowerCase();

const main = async () => {
  for (const food of foodList) {
    const engKeyword = slugify(food.kor_name);

    const { data, error: selectError } = await supabase
      .from('food_categories')
      .select('id')
      .eq('kor_name', food.kor_name)
      .maybeSingle();

    if (selectError) {
      console.error(`\u274c Select failed: ${food.kor_name}`, selectError.message);
      continue;
    }

    if (data) {
      console.log(`\u26a0\ufe0f Already exists: ${food.kor_name}`);
      continue;
    }

    const { error } = await supabase.from('food_categories').insert({
      kor_name: food.kor_name,
      eng_keyword: engKeyword,
      type: food.type,
      round: 1,
    });

    if (error) {
      console.error(`\u274c Insert failed: ${food.kor_name}`, error.message);
    } else {
      console.log(`\u2705 Inserted: ${food.kor_name} (${engKeyword})`);
    }
  }

  console.log('\ud83c\udf89 All done!');
};

main().catch(console.error);
